### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by peeyushsrj** [mdlayher/wavepipe#17]
Please update dependencies to let this wavepipe work, as the follwing packages no longer exist (and  moved)
- code.google.com/p/go.crypto/bcrypt
- code.google.com/p/go.crypto/pbkdf2
- code.google.com/p/go.exp/fsnotify

**Comment by mdlayher** [comment]
Sorry, I am no longer maintaining this repo.  It was one of my first projects in Go, and although I did begin a rewrite at one point, I no longer have a need for it.  Feel free to fork if you'd like.
